### PR TITLE
8313765: Invalid CEN header (invalid zip64 extra data field size)

### PR DESCRIPTION
**Pull request by benty-amzn**
Backport of 8313765: Invalid CEN header (invalid zip64 extra data field size), [jdk11u-dev #2084](https://github.com/openjdk/jdk11u-dev/pull/2084) for the 11.0.20.1 patch release.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8313765](https://bugs.openjdk.org/browse/JDK-8313765): Invalid CEN header (invalid zip64 extra data field size) (**Bug** - P2)

### Reviewers
 * [Volker Simonis](https://openjdk.org/census#simonis) (@simonis - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u.git pull/77/head:pull/77` \
`$ git checkout pull/77`

Update a local copy of the PR: \
`$ git checkout pull/77` \
`$ git pull https://git.openjdk.org/jdk11u.git pull/77/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 77`

View PR using the GUI difftool: \
`$ git pr show -t 77`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u/pull/77.diff">https://git.openjdk.org/jdk11u/pull/77.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u/pull/77#issuecomment-1686978966)

### CODE REVIEW

**Comment by phohensee** [comment]
Needs the title fixed to "Backport <commit-id>" so the bot will recognize it properly.

**Review by simonis — APPROVED** [review]
Thanks for doing the downport!
Looks good to me.

**Pull request closed without merging**
