### PR TITLE
8028265: Add legacy tz tests to OpenJDK

### PR DESCRIPTION
**Pull request by alvdavi**
Clean backport of JDK-8028265, bringing timezone tests before updating timezone data to 2022c. All tests in `test/jdk/java/util/TimeZone` are passing

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8028265](https://bugs.openjdk.org/browse/JDK-8028265): Add legacy tz tests to OpenJDK

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u pull/55/head:pull/55` \
`$ git checkout pull/55`

Update a local copy of the PR: \
`$ git checkout pull/55` \
`$ git pull https://git.openjdk.org/jdk11u pull/55/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 55`

View PR using the GUI difftool: \
`$ git pr show -t 55`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u/pull/55.diff">https://git.openjdk.org/jdk11u/pull/55.diff</a>

</details>

### CODE REVIEW

**Comment by GoeLin** [comment]
Pre-submit failure: CompensatedSums, known to be failing eventually, unrelated.

**Comment by GoeLin** [comment]
@alvdavi please check the Pre-submit tests before labeling fix-request. I won't approve a change with failing tests.

**Comment by gnu-andrew** [comment]
I see `jdk11u-critical-yes` now

**Comment by GoeLin** [comment]
@alvdavi please integrate this change. Thanks.

**Pull request closed without merging**
