### PR TITLE
8337664: Distrust TLS server certificates issued after Oct 2024 and anchored by Entrust Root CAs

### PR DESCRIPTION
**Pull request by GoeLin**
I backport this for parity with 11.0.25-oracle.

src/java.base/share/classes/sun/security/validator/CADistrustPolicy.java
 * Resolved Copyright
src/java.base/share/classes/sun/security/validator/EntrustTLSPolicy.java
 * Removed debug argument from getFingerprint() as "8270946: X509CertImpl.getFingerprint should not return the empty String" is not in 11.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8339194](https://bugs.openjdk.org/browse/JDK-8339194) to be approved
- [x] [JDK-8337664](https://bugs.openjdk.org/browse/JDK-8337664) needs maintainer approval

### Issues
 * [JDK-8337664](https://bugs.openjdk.org/browse/JDK-8337664): Distrust TLS server certificates issued after Oct 2024 and anchored by Entrust Root CAs (**Enhancement** - P3 - Approved)
 * [JDK-8339194](https://bugs.openjdk.org/browse/JDK-8339194): Distrust TLS server certificates issued after Oct 2024 and anchored by Entrust Root CAs (**CSR**)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u.git pull/95/head:pull/95` \
`$ git checkout pull/95`

Update a local copy of the PR: \
`$ git checkout pull/95` \
`$ git pull https://git.openjdk.org/jdk11u.git pull/95/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 95`

View PR using the GUI difftool: \
`$ git pr show -t 95`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u/pull/95.diff">https://git.openjdk.org/jdk11u/pull/95.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u/pull/95#issuecomment-2331299581)

### CODE REVIEW

**Comment by GoeLin** [comment]
GHA failures: well known sprintf build issues. Unrelated.

**Review by phohensee — APPROVED** [review]

**Comment by phohensee** [comment]
I assume this is a critical fix because it's against jdk11u rather than jdk11u-dev.

**Comment by GoeLin** [comment]
GHA failure: macos: well known sprintf build issue

**Comment by GoeLin** [comment]
Yes, according to the crypto roadmap this must be in the October update.

**Pull request closed without merging**
