### PR TITLE
8292260: [BACKOUT] JDK-8279219: [REDO] C2 crash when allocating array of size too large

### PR DESCRIPTION
**Pull request by jerboaa**
PR to backout the change of [JDK-8279219](https://bugs.openjdk.org/browse/JDK-8279219). I'll change this to the proper backport title once JDK 19 backout is done.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292260](https://bugs.openjdk.org/browse/JDK-8292260): [BACKOUT] JDK-8279219: [REDO] C2 crash when allocating array of size too large

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u pull/49/head:pull/49` \
`$ git checkout pull/49`

Update a local copy of the PR: \
`$ git checkout pull/49` \
`$ git pull https://git.openjdk.org/jdk11u pull/49/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 49`

View PR using the GUI difftool: \
`$ git pr show -t 49`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u/pull/49.diff">https://git.openjdk.org/jdk11u/pull/49.diff</a>

</details>

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
Backout looks clean.

I also applied it and checked delta between this PR and the commit before 8279219. Affected files look identical apart from opto/split_if.cpp which was modified with as part of "8280799: С2: assert(false) failed: cyclic dependency prevents range check elimination" 22f8e216eef4efc2685986067dee10e24301b6dc

**Comment by vnkozlov** [comment]
@jerboaa I don't see corresponding backport bug linked to JDK-8292260.

**Comment by RealCLanger** [comment]
> @jerboaa I don't see corresponding backport bug linked to JDK-8292260.

I believe a backport bug will be created once we merge this back into the master branch. Let's see what happens. If Skara bots fail to do so, we need to create one manually.

**Comment by jerboaa** [comment]
We've only integrated this into the `jdk11.0.16.1` branch and that might confuse SKARA tooling. At least I've observed that the version bump bug didn't get resolved properly by the bots too. Not sure what's going on. We'll likely have to create on manually for 11.0.16.1.

**Comment by kevinrushforth** [comment]
> We've only integrated this into the jdk11.0.16.1 branch and that might confuse SKARA tooling. At least I've observed that the version bump bug didn't get resolved properly by the bots too. Not sure what's going on. We'll likely have to create on manually for 11.0.16.1.

@jerboaa I alerted @erikj79 who has discovered the reason that the JBS backport record wasn't created and the commit URL wasn't added as a comment. It should be fixed shortly, so you should not have to manually create the record.

**Comment by jerboaa** [comment]
@kevinrushforth OK. Thank you!

**Comment by RealCLanger** [comment]
> > We've only integrated this into the jdk11.0.16.1 branch and that might confuse SKARA tooling. At least I've observed that the version bump bug didn't get resolved properly by the bots too. Not sure what's going on. We'll likely have to create on manually for 11.0.16.1.
> 
> @jerboaa I alerted @erikj79 who has discovered the reason that the JBS backport record wasn't created and the commit URL wasn't added as a comment. It should be fixed shortly, so you should not have to manually create the record.

Looks like this is resolved now. Good to know that the Skara bots also operate on branches.

**Pull request closed without merging**
