### PR TITLE
8305113: (tz) Update Timezone Data to 2023c

### PR DESCRIPTION
**Pull request by rgithubli**
Backport tz2023c.

The backport is NOT clean:

- I had to drop [src/java.base/share/classes/sun/util/calendar/ZoneInfoFile.java](https://github.com/openjdk/jdk/commit/ed9592c6e81f82e2bf6508ce45ba15aad8232181#diff-88f8bdbe16f63d17eca77e3af484f7491244be70448029a19548032640dc3475) in the original patch, since 11 already has that block of code (same code. It just writes out enums as numbers): [link](https://github.com/openjdk/jdk11u/blob/master/src/java.base/share/classes/sun/util/calendar/ZoneInfoFile.java#L632-L636). The code was deleted in 18 for https://bugs.openjdk.org/browse/JDK-8274864 and now added back as part of tz 2023c.

- Also resolved minor conflicts for test/jdk/java/util/TimeZone/TimeZoneTest.java: copyright year and `@bug` JBS tags.

Testing: jtreg tier1 passed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305113](https://bugs.openjdk.org/browse/JDK-8305113): (tz) Update Timezone Data to 2023c

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk11u.git pull/71/head:pull/71` \
`$ git checkout pull/71`

Update a local copy of the PR: \
`$ git checkout pull/71` \
`$ git pull https://git.openjdk.org/jdk11u.git pull/71/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 71`

View PR using the GUI difftool: \
`$ git pr show -t 71`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk11u/pull/71.diff">https://git.openjdk.org/jdk11u/pull/71.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk11u/pull/71#issuecomment-1502385289)

### CODE REVIEW

**Comment by rgithubli** [comment]
Didn't turn on pre-submit testing in my repo initially so the test skipped. Manual run: https://github.com/rgithubli/jdk11u/actions/runs/4661745091

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by rgithubli** [comment]
Sorry for missing the context. We wanted this tz data change to be added as part of q2 release. In tz2023c it seems we're reverting [2023b](https://bugs.openjdk.org/browse/JDK-8304854) which will take effect in 04/20/23.

**Comment by rgithubli** [comment]
@gnu-andrew just left a comment in 17u: https://github.com/openjdk/jdk17u/pull/368#issuecomment-1505760376

> JDK-8274864 should be backported first for 11u & 17u, as is the case in Oracle's forks; see https://github.com/openjdk/jdk17u-dev/pull/1240

**Pull request closed without merging**
