### PR TITLE
8273235: tools/launcher/HelpFlagsTest.java Fails on Windows 32bit

### PR DESCRIPTION
**Pull request by adamfarley**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8273235](https://bugs.openjdk.java.net/browse/JDK-8273235): tools/launcher/HelpFlagsTest.java Fails on Windows 32bit

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk11u pull/17/head:pull/17` \
`$ git checkout pull/17`

Update a local copy of the PR: \
`$ git checkout pull/17` \
`$ git pull https://git.openjdk.java.net/jdk11u pull/17/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 17`

View PR using the GUI difftool: \
`$ git pr show -t 17`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk11u/pull/17.diff">https://git.openjdk.java.net/jdk11u/pull/17.diff</a>

</details>

### CODE REVIEW

**Comment by adamfarley** [comment]
Sponsor requested please.

**Comment by RealCLanger** [comment]
Hi, @adamfarley,

that's not quite correct process wise. You need to flag the JBS bug with jdk11u-fix-request to request maintainer approval for this backport. And please also add a fix request comment, stating why you want to do this backport, what testing you did and how you assess the risk. Only when a maintainer adds a jdk11u-fix-yes label, you can comment with /integrate.
Furthermore, for JDK 11 update, the correct repository for doing standard backports is [jdk11u-dev](https://github.com/openjdk/jdk11u-dev). jdk11u may only be used for critical patches during rampdown phase. So, please close this one and do a PR in jdk11u-dev.

Thanks
Christoph

**Comment by adamfarley** [comment]
Thanks for the help @RealCLanger 

Will do. :)

**Pull request closed without merging**
